# File‑upload restrictions
attachment_file_types_restricted: false
attachment_file_types:
  - "txt"
  - "pdf"
  - "csv"
  - "md"
  - "json"
  - "log"
  - "py"
  - "sql"
  - "patch"
  - "LICENSE"
  - "toml"
  - "gitignore"

# Color palette & symbols
ui_colors:
  red:
    value: "#dc3545"
    symbol: "🔴"
  orange:
    value: "#fd7e14"
    symbol: "🟠"
  yellow:
    value: "#FFFF00"
    symbol: "🟡"
  green:
    value: "#198754"
    symbol: "🟢"
  blue:
    value: "#0000FF"
    symbol: "🔵"
  purple:
    value: "#842029"
    symbol: "🟣"
  grey:
    value: "#6c757d"
    symbol: "⚪"
  brown:
    value: "#A52A2A"
    symbol: "🟤"
  black:
    value: "#000000"
    symbol: "⚫️"
  default:
    value: "#6c757d"
    symbol: "⚪"